import { PrismaClient } from '@prisma/client';
import { Tournament } from '../constants';

const prisma = new PrismaClient();

const MM2022tournament: Tournament = {
  name: 'Jalkapallon MM-kisat 2022',
  startingDate: new Date('2022-11-20T18:00:00+02:00'),
  extraPredictions: {
    mostGoals: '',
    topFour: [],
    mostCards: '',
    fastestGoal: null,
    highestScoring: null,
    headToHead: [
      {
        contestants: ['Englanti', 'Saksa'],
        winner: null,
        type: 'winner',
      },
      {
        contestants: ['Ranska', 'Espanja'],
        winner: null,
        type: 'winner',
      },
      {
        contestants: ['Brasilia', 'Argentina'],
        winner: null,
        type: 'winner',
      },
      {
        contestants: ['Kane', 'Mbappé'],
        winner: null,
        type: 'goal',
      },
      {
        contestants: ['Messi', 'Ronaldo'],
        winner: null,
        type: 'goal',
      },
      {
        contestants: ['Neymar', 'de Bruyne'],
        winner: null,
        type: 'pass',
      },
    ],
  },
  groups: [
    {
      name: 'A',
      matches: [
        {
          home: 'Qatar',
          away: 'Ecuador',
          date: new Date('2022-11-20T18:00:00+02:00'),
          id: 1,
          result: null,
        },
        {
          home: 'Senegal',
          away: 'Hollanti',
          date: new Date('2022-11-21T18:00:00+02:00'),
          id: 2,
          result: null,
        },
        {
          home: 'Qatar',
          away: 'Senegal',
          date: new Date('2022-11-25T15:00:00+02:00'),
          id: 3,
          result: null,
        },
        {
          home: 'Hollanti',
          away: 'Ecuador',
          date: new Date('2022-11-25T18:00:00+02:00'),
          id: 4,
          result: null,
        },
        {
          home: 'Hollanti',
          away: 'Qatar',
          date: new Date('2022-11-29T17:00:00+02:00'),
          id: 5,
          result: null,
        },
        {
          home: 'Ecuador',
          away: 'Senegal',
          date: new Date('2022-11-29T17:00:00+02:00'),
          id: 6,
          result: null,
        },
      ],
      teams: [
        { name: 'Qatar', points: 0, predictedPoints: 0 },
        { name: 'Ecuador', points: 0, predictedPoints: 0 },
        { name: 'Senegal', points: 0, predictedPoints: 0 },
        { name: 'Hollanti', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'B',
      matches: [
        {
          home: 'Englanti',
          away: 'Iran',
          date: new Date('2022-11-21T15:00:00+02:00'),
          id: 7,
          result: null,
        },
        {
          home: 'Usa',
          away: 'Wales',
          date: new Date('2022-11-21T21:00:00+02:00'),
          id: 8,
          result: null,
        },
        {
          home: 'Wales',
          away: 'Iran',
          date: new Date('2022-11-25T12:00:00+02:00'),
          id: 9,
          result: null,
        },
        {
          home: 'Englanti',
          away: 'Usa',
          date: new Date('2022-11-25T21:00:00+02:00'),
          id: 10,
          result: null,
        },
        {
          home: 'Wales',
          away: 'Englanti',
          date: new Date('2022-11-29T21:00:00+02:00'),
          id: 11,
          result: null,
        },
        {
          home: 'Iran',
          away: 'Usa',
          date: new Date('2022-11-29T21:00:00+02:00'),
          id: 12,
          result: null,
        },
      ],
      teams: [
        { name: 'Englanti', points: 0, predictedPoints: 0 },
        { name: 'Iran', points: 0, predictedPoints: 0 },
        { name: 'Usa', points: 0, predictedPoints: 0 },
        { name: 'Wales', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'C',
      matches: [
        {
          home: 'Argentina',
          away: 'Saudi Arabia',
          date: new Date('2022-11-22T12:00:00+02:00'),
          id: 13,
          result: null,
        },
        {
          home: 'Meksiko',
          away: 'Puola',
          date: new Date('2022-11-22T18:00:00+02:00'),
          id: 14,
          result: null,
        },
        {
          home: 'Puola',
          away: 'Saudi Arabia',
          date: new Date('2022-11-26T15:00:00+02:00'),
          id: 15,
          result: null,
        },
        {
          home: 'Argentina',
          away: 'Meksiko',
          date: new Date('2022-11-26T21:00:00+02:00'),
          id: 16,
          result: null,
        },
        {
          home: 'Puola',
          away: 'Argentina',
          date: new Date('2022-11-30T21:00:00+02:00'),
          id: 17,
          result: null,
        },
        {
          home: 'Saudi Arabia',
          away: 'Meksiko',
          date: new Date('2022-11-30T21:00:00+02:00'),
          id: 18,
          result: null,
        },
      ],
      teams: [
        { name: 'Argentina', points: 0, predictedPoints: 0 },
        { name: 'Saudi Arabia', points: 0, predictedPoints: 0 },
        { name: 'Meksiko', points: 0, predictedPoints: 0 },
        { name: 'Puola', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'D',
      matches: [
        {
          home: 'Tanska',
          away: 'Tunisia',
          date: new Date('2022-11-22T15:00:00+02:00'),
          id: 19,
          result: null,
        },
        {
          home: 'Ranska',
          away: 'Australia',
          date: new Date('2022-11-22T21:00:00+02:00'),
          id: 20,
          result: null,
        },
        {
          home: 'Tunisia',
          away: 'Australia',
          date: new Date('2022-11-26T12:00:00+02:00'),
          id: 21,
          result: null,
        },
        {
          home: 'Ranska',
          away: 'Tanska',
          date: new Date('2022-11-26T18:00:00+02:00'),
          id: 22,
          result: null,
        },
        {
          home: 'Tunisia',
          away: 'Ranska',
          date: new Date('2022-11-30T17:00:00+02:00'),
          id: 23,
          result: null,
        },
        {
          home: 'Australia',
          away: 'Tanska',
          date: new Date('2022-11-30T17:00:00+02:00'),
          id: 24,
          result: null,
        },
      ],
      teams: [
        { name: 'Ranska', points: 0, predictedPoints: 0 },
        { name: 'Tanska', points: 0, predictedPoints: 0 },
        { name: 'Tunisia', points: 0, predictedPoints: 0 },
        { name: 'Australia', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'E',
      matches: [
        {
          home: 'Saksa',
          away: 'Japani',
          date: new Date('2022-11-23T15:00:00+02:00'),
          id: 25,
          result: null,
        },
        {
          home: 'Espanja',
          away: 'Costa Rica',
          date: new Date('2022-11-23T18:00:00+02:00'),
          id: 26,
          result: null,
        },
        {
          home: 'Japani',
          away: 'Costa Rica',
          date: new Date('2022-11-27T12:00:00+02:00'),
          id: 27,
          result: null,
        },
        {
          home: 'Espanja',
          away: 'Saksa',
          date: new Date('2022-11-27T21:00:00+02:00'),
          id: 28,
          result: null,
        },
        {
          home: 'Japani',
          away: 'Espanja',
          date: new Date('2022-12-01T21:00:00+02:00'),
          id: 29,
          result: null,
        },
        {
          home: 'Costa Rica',
          away: 'Saksa',
          date: new Date('2022-12-01T21:00:00+02:00'),
          id: 30,
          result: null,
        },
      ],
      teams: [
        { name: 'Espanja', points: 0, predictedPoints: 0 },
        { name: 'Saksa', points: 0, predictedPoints: 0 },
        { name: 'Japani', points: 0, predictedPoints: 0 },
        { name: 'Costa Rica', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'F',
      matches: [
        {
          home: 'Marokko',
          away: 'Kroatia',
          date: new Date('2022-11-23T12:00:00+02:00'),
          id: 31,
          result: null,
        },
        {
          home: 'Belgia',
          away: 'Kanada',
          date: new Date('2022-11-23T21:00:00+02:00'),
          id: 32,
          result: null,
        },
        {
          home: 'Belgia',
          away: 'Marokko',
          date: new Date('2022-11-27T15:00:00+02:00'),
          id: 33,
          result: null,
        },
        {
          home: 'Kroatia',
          away: 'Kanada',
          date: new Date('2022-11-27T18:00:00+02:00'),
          id: 34,
          result: null,
        },
        {
          home: 'Kanada',
          away: 'Marokko',
          date: new Date('2022-12-01T17:00:00+02:00'),
          id: 35,
          result: null,
        },
        {
          home: 'Kroatia',
          away: 'Belgia',
          date: new Date('2022-12-01T17:00:00+02:00'),
          id: 36,
          result: null,
        },
      ],
      teams: [
        { name: 'Belgia', points: 0, predictedPoints: 0 },
        { name: 'Kanada', points: 0, predictedPoints: 0 },
        { name: 'Marokko', points: 0, predictedPoints: 0 },
        { name: 'Kroatia', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'G',
      matches: [
        {
          home: 'Sveitsi',
          away: 'Kamerun',
          date: new Date('2022-11-24T12:00:00+02:00'),
          id: 37,
          result: null,
        },
        {
          home: 'Brasilia',
          away: 'Serbia',
          date: new Date('2022-11-24T21:00:00+02:00'),
          id: 38,
          result: null,
        },
        {
          home: 'Kamerun',
          away: 'Serbia',
          date: new Date('2022-11-28T12:00:00+02:00'),
          id: 39,
          result: null,
        },
        {
          home: 'Brasilia',
          away: 'Sveitsi',
          date: new Date('2022-11-28T18:00:00+02:00'),
          id: 40,
          result: null,
        },
        {
          home: 'Kamerun',
          away: 'Brasilia',
          date: new Date('2022-12-02T21:00:00+02:00'),
          id: 41,
          result: null,
        },
        {
          home: 'Serbia',
          away: 'Sveitsi',
          date: new Date('2022-12-02T21:00:00+02:00'),
          id: 42,
          result: null,
        },
      ],
      teams: [
        { name: 'Brasilia', points: 0, predictedPoints: 0 },
        { name: 'Serbia', points: 0, predictedPoints: 0 },
        { name: 'Sveitsi', points: 0, predictedPoints: 0 },
        { name: 'Kamerun', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'H',
      matches: [
        {
          home: 'Uruguay',
          away: 'Etelä-Korea',
          date: new Date('2022-11-24T15:00:00+02:00'),
          id: 43,
          result: null,
        },
        {
          home: 'Portugali',
          away: 'Ghana',
          date: new Date('2022-11-24T18:00:00+02:00'),
          id: 44,
          result: null,
        },
        {
          home: 'Etelä-Korea',
          away: 'Ghana',
          date: new Date('2022-11-28T15:00:00+02:00'),
          id: 45,
          result: null,
        },
        {
          home: 'Portugali',
          away: 'Uruguay',
          date: new Date('2022-11-28T21:00:00+02:00'),
          id: 46,
          result: null,
        },
        {
          home: 'Ghana',
          away: 'Uruguay',
          date: new Date('2022-12-02T17:00:00+02:00'),
          id: 47,
          result: null,
        },
        {
          home: 'Etelä-Korea',
          away: 'Portugali',
          date: new Date('2022-12-02T17:00:00+02:00'),
          id: 48,
          result: null,
        },
      ],
      teams: [
        { name: 'Portugali', points: 0, predictedPoints: 0 },
        { name: 'Ghana', points: 0, predictedPoints: 0 },
        { name: 'Uruguay', points: 0, predictedPoints: 0 },
        { name: 'Etelä-Korea', points: 0, predictedPoints: 0 },
      ],
    },
  ],
  playoffMatches: [],
};
const EM2024tournament: Tournament = {
  name: 'Jalkapallon EM-kisat 2024',
  startingDate: new Date('2024-06-14T22:00:00+03:00'),
  extraPredictions: {
    mostGoals: '',
    topFour: [],
    mostCards: '',
    fastestGoal: null,
    highestScoring: null,
    headToHead: [
      {
        contestants: ['Espanja', 'Saksa'],
        winner: null,
        type: 'winner',
      },
      {
        contestants: ['Ranska', 'Englanti'],
        winner: null,
        type: 'winner',
      },
      {
        contestants: ['Kane', 'Mbappé'],
        winner: null,
        type: 'goal',
      },
      {
        contestants: ['Griezmann', 'Bellingham'],
        winner: null,
        type: 'goal',
      },
      {
        contestants: ['Ronaldo', 'Foden'],
        winner: null,
        type: 'goal',
      },
      {
        contestants: ['Bruno F.', 'de Bruyne'],
        winner: null,
        type: 'pass',
      },
    ],
  },
  groups: [
    {
      name: 'A',
      matches: [
        {
          home: 'Saksa',
          away: 'Skotlanti',
          date: new Date('2024-06-14T22:00:00+03:00'),
          id: 1,
          result: null,
        },
        {
          home: 'Unkari',
          away: 'Sveitsi',
          date: new Date('2024-06-15T16:00:00+03:00'),
          id: 2,
          result: null,
        },
        {
          home: 'Saksa',
          away: 'Unkari',
          date: new Date('2024-06-19T19:00:00+03:00'),
          id: 3,
          result: null,
        },
        {
          home: 'Skotlanti',
          away: 'Sveitsi',
          date: new Date('2024-06-19T22:00:00+03:00'),
          id: 4,
          result: null,
        },
        {
          home: 'Sveitsi',
          away: 'Saksa',
          date: new Date('2024-06-23T22:00:00+03:00'),
          id: 5,
          result: null,
        },
        {
          home: 'Skotlanti',
          away: 'Unkari',
          date: new Date('2024-06-23T22:00:00+03:00'),
          id: 6,
          result: null,
        },
      ],
      teams: [
        { name: 'Saksa', points: 0, predictedPoints: 0 },
        { name: 'Skotlanti', points: 0, predictedPoints: 0 },
        { name: 'Unkari', points: 0, predictedPoints: 0 },
        { name: 'Sveitsi', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'B',
      matches: [
        {
          home: 'Espanja',
          away: 'Kroatia',
          date: new Date('2024-06-15T19:00:00+03:00'),
          id: 7,
          result: null,
        },
        {
          home: 'Italia',
          away: 'Albania',
          date: new Date('2024-06-15T22:00:00+03:00'),
          id: 8,
          result: null,
        },
        {
          home: 'Kroatia',
          away: 'Albania',
          date: new Date('2024-06-19T16:00:00+03:00'),
          id: 9,
          result: null,
        },
        {
          home: 'Espanja',
          away: 'Italia',
          date: new Date('2024-06-20T22:00:00+03:00'),
          id: 10,
          result: null,
        },
        {
          home: 'Albania',
          away: 'Espanja',
          date: new Date('2024-06-24T22:00:00+03:00'),
          id: 11,
          result: null,
        },
        {
          home: 'Kroatia',
          away: 'Italia',
          date: new Date('2024-06-24T22:00:00+03:00'),
          id: 12,
          result: null,
        },
      ],
      teams: [
        { name: 'Espanja', points: 0, predictedPoints: 0 },
        { name: 'Kroatia', points: 0, predictedPoints: 0 },
        { name: 'Italia', points: 0, predictedPoints: 0 },
        { name: 'Albania', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'C',
      matches: [
        {
          home: 'Slovenia',
          away: 'Tanska',
          date: new Date('2024-06-16T19:00:00+03:00'),
          id: 13,
          result: null,
        },
        {
          home: 'Serbia',
          away: 'Englanti',
          date: new Date('2024-06-16T22:00:00+03:00'),
          id: 14,
          result: null,
        },
        {
          home: 'Slovenia',
          away: 'Serbia',
          date: new Date('2024-06-20T16:00:00+03:00'),
          id: 15,
          result: null,
        },
        {
          home: 'Tanska',
          away: 'Englanti',
          date: new Date('2024-06-20T19:00:00+03:00'),
          id: 16,
          result: null,
        },
        {
          home: 'Englanti',
          away: 'Slovenia',
          date: new Date('2024-06-25T22:00:00+03:00'),
          id: 17,
          result: null,
        },
        {
          home: 'Tanska',
          away: 'Serbia',
          date: new Date('2024-06-25T22:00:00+03:00'),
          id: 18,
          result: null,
        },
      ],
      teams: [
        { name: 'Slovenia', points: 0, predictedPoints: 0 },
        { name: 'Tanska', points: 0, predictedPoints: 0 },
        { name: 'Serbia', points: 0, predictedPoints: 0 },
        { name: 'Englanti', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'D',
      matches: [
        {
          home: 'Puola',
          away: 'Hollanti',
          date: new Date('2024-06-16T16:00:00+03:00'),
          id: 19,
          result: null,
        },
        {
          home: 'Itävalta',
          away: 'Ranska',
          date: new Date('2024-06-17T22:00:00+03:00'),
          id: 20,
          result: null,
        },
        {
          home: 'Puola',
          away: 'Itävalta',
          date: new Date('2024-06-21T19:00:00+03:00'),
          id: 21,
          result: null,
        },
        {
          home: 'Hollanti',
          away: 'Ranska',
          date: new Date('2024-06-21T22:00:00+03:00'),
          id: 22,
          result: null,
        },
        {
          home: 'Hollanti',
          away: 'Itävalta',
          date: new Date('2024-06-25T19:00:00+03:00'),
          id: 23,
          result: null,
        },
        {
          home: 'Ranska',
          away: 'Puola',
          date: new Date('2024-06-25T19:00:00+03:00'),
          id: 24,
          result: null,
        },
      ],
      teams: [
        { name: 'Hollanti', points: 0, predictedPoints: 0 },
        { name: 'Ranska', points: 0, predictedPoints: 0 },
        { name: 'Puola', points: 0, predictedPoints: 0 },
        { name: 'Itävalta', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'E',
      matches: [
        {
          home: 'Romania',
          away: 'Ukraina',
          date: new Date('2024-06-17T16:00:00+03:00'),
          id: 25,
          result: null,
        },
        {
          home: 'Belgia',
          away: 'Slovakia',
          date: new Date('2024-06-17T19:00:00+03:00'),
          id: 26,
          result: null,
        },
        {
          home: 'Slovakia',
          away: 'Ukraina',
          date: new Date('2024-06-21T16:00:00+03:00'),
          id: 27,
          result: null,
        },
        {
          home: 'Belgia',
          away: 'Romania',
          date: new Date('2024-06-22T22:00:00+03:00'),
          id: 28,
          result: null,
        },
        {
          home: 'Slovakia',
          away: 'Romania',
          date: new Date('2024-06-26T19:00:00+03:00'),
          id: 29,
          result: null,
        },
        {
          home: 'Ukraina',
          away: 'Belgia',
          date: new Date('2024-06-26T19:00:00+03:00'),
          id: 30,
          result: null,
        },
      ],
      teams: [
        { name: 'Ukraina', points: 0, predictedPoints: 0 },
        { name: 'Slovakia', points: 0, predictedPoints: 0 },
        { name: 'Belgia', points: 0, predictedPoints: 0 },
        { name: 'Romania', points: 0, predictedPoints: 0 },
      ],
    },
    {
      name: 'F',
      matches: [
        {
          home: 'Turkki',
          away: 'Georgia',
          date: new Date('2024-06-18T19:00:00+03:00'),
          id: 31,
          result: null,
        },
        {
          home: 'Portugali',
          away: 'Tsekki',
          date: new Date('2024-06-18T22:00:00+03:00'),
          id: 32,
          result: null,
        },
        {
          home: 'Georgia',
          away: 'Tsekki',
          date: new Date('2024-06-22T16:00:00+03:00'),
          id: 33,
          result: null,
        },
        {
          home: 'Turkki',
          away: 'Portugali',
          date: new Date('2024-06-22T19:00:00+03:00'),
          id: 34,
          result: null,
        },
        {
          home: 'Georgia',
          away: 'Portugali',
          date: new Date('2024-06-26T22:00:00+03:00'),
          id: 35,
          result: null,
        },
        {
          home: 'Tsekki',
          away: 'Turkki',
          date: new Date('2024-06-26T22:00:00+03:00'),
          id: 36,
          result: null,
        },
      ],
      teams: [
        { name: 'Portugali', points: 0, predictedPoints: 0 },
        { name: 'Tsekki', points: 0, predictedPoints: 0 },
        { name: 'Georgia', points: 0, predictedPoints: 0 },
        { name: 'Turkki', points: 0, predictedPoints: 0 },
      ],
    },
  ],
  playoffMatches: [
    {
      home: 'Espanja',
      away: 'Georgia',
      id: 1,
      result: null,
      date: new Date('2024-06-30T22:00:00+03:00'),
    },
    {
      home: 'Saksa',
      away: 'Tanska',
      id: 2,
      result: null,
      date: new Date('2024-06-29T22:00:00+03:00'),
    },
    {
      home: 'Portugali',
      away: 'Slovenia',
      id: 3,
      result: null,
      date: new Date('2024-07-01T22:00:00+03:00'),
    },
    {
      home: 'Ranska',
      away: 'Belgia',
      id: 4,
      result: null,
      date: new Date('2024-07-01T19:00:00+03:00'),
    },
    {
      home: '',
      away: '',
      id: 5,
      result: null,
      date: new Date('2024-07-05T19:00:00+03:00'),
    },
    {
      home: '',
      away: '',
      id: 6,
      result: null,
      date: new Date('2024-07-05T22:00:00+03:00'),
    },
    {
      home: '',
      away: '',
      id: 7,
      result: null,
      date: new Date('2024-07-09T22:00:00+03:00'),
    },
    {
      home: 'Romania',
      away: 'Hollanti',
      id: 8,
      result: null,
      date: new Date('2024-07-02T19:00:00+03:00'),
    },
    {
      home: 'Itävalta',
      away: 'Turkki',
      id: 9,
      result: null,
      date: new Date('2024-07-02T22:00:00+03:00'),
    },
    {
      home: 'Englanti',
      away: 'Slovakia',
      id: 10,
      result: null,
      date: new Date('2024-06-30T19:00:00+03:00'),
    },
    {
      home: 'Sveitsi',
      away: 'Italia',
      id: 11,
      result: null,
      date: new Date('2024-06-29T19:00:00+03:00'),
    },
    {
      home: '',
      away: '',
      id: 12,
      result: null,
      date: new Date('2024-07-06T22:00:00+03:00'),
    },
    {
      home: '',
      away: '',
      id: 13,
      result: null,
      date: new Date('2024-07-06T19:00:00+03:00'),
    },
    {
      home: '',
      away: '',
      id: 14,
      result: null,
      date: new Date('2024-07-10T22:00:00+03:00'),
    },
    {
      home: '',
      away: '',
      id: 15,
      result: null,
      date: new Date('2024-07-14T22:00:00+03:00'),
    },
  ],
};

async function main() {
  const tournamentJson = MM2022tournament;
  const tournamentExtraPredictionsJson = MM2022tournament.extraPredictions;
  await prisma.tournament.createMany({
    data: [
      {
        tournamentData: tournamentJson as any,
        lastUpdated: null,
        extraPredictions: tournamentExtraPredictionsJson as any,
      },
      {
        tournamentData: EM2024tournament as any,
        lastUpdated: null,
        extraPredictions: EM2024tournament.extraPredictions as any,
      },
    ],
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
